# Generated by Django 3.0.4 on 2020-03-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lock',
            old_name='status',
            new_name='security',
        ),
        migrations.AddField(
            model_name='ac',
            name='mode',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Auto'), (1, 'Cool'), (2, 'Fan')], default=0),
            preserve_default=False,
        ),
    ]
